# Generated by Django 4.0.5 on 2023-01-21 15:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sondage', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='choice',
            name='vote',
        ),
        migrations.AddField(
            model_name='choice',
            name='votes',
            field=models.IntegerField(default=0),
        ),
    ]
